import type { MaintenanceRecord } from "../types";

export const mockMaintenanceRecords: MaintenanceRecord[] = [
  {
    id: "MNT-001",
    vehicleId: "VEH-001",
    date: "2024-08-11",
    serviceType: "Oil Change",
    cost: 89.99,
    mileage: 50882,
    technicianNotes:
      "Standard oil change, filter replaced. All systems checked.",
  },
  {
    id: "MNT-002",
    vehicleId: "VEH-001",
    date: "2024-06-15",
    serviceType: "Tire Replacement",
    cost: 450.0,
    mileage: 48500,
    technicianNotes: "Replaced all 4 tires. Alignment checked and adjusted.",
  },
  {
    id: "MNT-003",
    vehicleId: "VEH-001",
    date: "2024-04-20",
    serviceType: "Brake Service",
    cost: 320.5,
    mileage: 46000,
    technicianNotes:
      "Front brake pads and rotors replaced. Rear brakes inspected - good condition.",
  },
  {
    id: "MNT-004",
    vehicleId: "VEH-001",
    date: "2024-02-10",
    serviceType: "Inspection",
    cost: 75.0,
    mileage: 43200,
    technicianNotes: "Annual inspection completed. All systems passed.",
  },
  {
    id: "MNT-005",
    vehicleId: "VEH-004",
    date: "2024-12-15",
    serviceType: "Oil Change",
    cost: 89.99,
    mileage: 15892,
    technicianNotes: "Oil change completed. Air filter replaced.",
  },
  {
    id: "MNT-006",
    vehicleId: "VEH-004",
    date: "2024-10-01",
    serviceType: "General Maintenance",
    cost: 150.0,
    mileage: 12000,
    technicianNotes: "Fluid levels checked, belts inspected. All good.",
  },
  {
    id: "MNT-007",
    vehicleId: "VEH-005",
    date: "2024-10-13",
    serviceType: "Oil Change",
    cost: 89.99,
    mileage: 44236,
    technicianNotes: "Standard service completed.",
  },
  {
    id: "MNT-008",
    vehicleId: "VEH-006",
    date: "2024-10-27",
    serviceType: "Battery Replacement",
    cost: 180.0,
    mileage: 117258,
    technicianNotes:
      "Battery replaced. Charging system tested - working properly.",
  },
  {
    id: "MNT-009",
    vehicleId: "VEH-007",
    date: "2024-10-18",
    serviceType: "Engine Repair",
    cost: 850.0,
    mileage: 36380,
    technicianNotes:
      "Engine diagnostic performed. Replaced spark plugs and ignition coils.",
  },
  {
    id: "MNT-010",
    vehicleId: "VEH-008",
    date: "2024-01-09",
    serviceType: "Oil Change",
    cost: 89.99,
    mileage: 85917,
    technicianNotes: "Oil change and inspection completed.",
  },
  {
    id: "MNT-011",
    vehicleId: "VEH-009",
    date: "2025-12-20",
    serviceType: "Oil Change",
    cost: 95.0,
    mileage: 30000,
    technicianNotes: "Monthly service completed.",
  },
  {
    id: "MNT-012",
    vehicleId: "VEH-010",
    date: "2025-11-15",
    serviceType: "Brake Service",
    cost: 380.0,
    mileage: 45000,
    technicianNotes: "Brake pads replaced on all wheels.",
  },
  {
    id: "MNT-013",
    vehicleId: "VEH-011",
    date: "2025-10-10",
    serviceType: "Tire Replacement",
    cost: 520.0,
    mileage: 60000,
    technicianNotes: "All 4 tires replaced, alignment done.",
  },
  {
    id: "MNT-014",
    vehicleId: "VEH-012",
    date: "2025-09-05",
    serviceType: "Engine Repair",
    cost: 1200.0,
    mileage: 75000,
    technicianNotes: "Major engine service, belts and hoses replaced.",
  },
  {
    id: "MNT-015",
    vehicleId: "VEH-013",
    date: "2025-08-25",
    serviceType: "General Maintenance",
    cost: 200.0,
    mileage: 35000,
    technicianNotes: "Comprehensive inspection and fluid top-up.",
  },
  {
    id: "MNT-016",
    vehicleId: "VEH-014",
    date: "2025-07-18",
    serviceType: "Battery Replacement",
    cost: 195.0,
    mileage: 28000,
    technicianNotes: "Battery replaced, charging system tested.",
  },
  {
    id: "MNT-017",
    vehicleId: "VEH-015",
    date: "2025-12-05",
    serviceType: "Inspection",
    cost: 85.0,
    mileage: 40000,
    technicianNotes: "Annual safety inspection passed.",
  },
  {
    id: "MNT-018",
    vehicleId: "VEH-016",
    date: "2025-11-22",
    serviceType: "Oil Change",
    cost: 92.5,
    mileage: 55000,
    technicianNotes: "Oil change with synthetic oil.",
  },
  {
    id: "MNT-019",
    vehicleId: "VEH-017",
    date: "2025-10-28",
    serviceType: "Brake Service",
    cost: 350.0,
    mileage: 68000,
    technicianNotes: "Front and rear brake service completed.",
  },
  {
    id: "MNT-020",
    vehicleId: "VEH-018",
    date: "2025-09-12",
    serviceType: "General Maintenance",
    cost: 175.0,
    mileage: 42000,
    technicianNotes: "Routine maintenance and fluid check.",
  },
  {
    id: "MNT-021",
    vehicleId: "VEH-019",
    date: "2025-08-30",
    serviceType: "Oil Change",
    cost: 88.0,
    mileage: 38000,
    technicianNotes: "Standard oil change service.",
  },
  {
    id: "MNT-022",
    vehicleId: "VEH-020",
    date: "2025-07-25",
    serviceType: "Tire Replacement",
    cost: 480.0,
    mileage: 52000,
    technicianNotes: "Two front tires replaced.",
  },
  {
    id: "MNT-023",
    vehicleId: "VEH-021",
    date: "2025-12-10",
    serviceType: "Engine Repair",
    cost: 750.0,
    mileage: 65000,
    technicianNotes: "Engine tune-up and diagnostic.",
  },
  {
    id: "MNT-024",
    vehicleId: "VEH-022",
    date: "2025-11-05",
    serviceType: "Oil Change",
    cost: 90.0,
    mileage: 48000,
    technicianNotes: "Regular oil change service.",
  },
  {
    id: "MNT-025",
    vehicleId: "VEH-023",
    date: "2025-10-15",
    serviceType: "General Maintenance",
    cost: 160.0,
    mileage: 55000,
    technicianNotes: "Fluid check and top-up.",
  },
  {
    id: "MNT-026",
    vehicleId: "VEH-024",
    date: "2025-09-20",
    serviceType: "Brake Service",
    cost: 320.0,
    mileage: 72000,
    technicianNotes: "Brake inspection and pad replacement.",
  },
  {
    id: "MNT-027",
    vehicleId: "VEH-025",
    date: "2025-08-10",
    serviceType: "Inspection",
    cost: 75.0,
    mileage: 33000,
    technicianNotes: "Safety inspection completed.",
  },
];

export const getMaintenanceByVehicleId = (
  vehicleId: string
): MaintenanceRecord[] => {
  return mockMaintenanceRecords
    .filter((record) => record.vehicleId === vehicleId)
    .sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());
};
